module Test

from "string" include String
from "stack" include Stack
from "map" include Map
from "option" include Option
from "buffer" include Buffer
from "result" include Result

use Stack.*

provide record TestDefinition {
    name: String,
    assertions: Stack<() => Option<String>>
}

let tests = Map.make()

let currentTestDef = box({
        name: "",
        assertions: Stack.make()
    })

provide let def = (name, callback) => { 
    currentTestDef := {
        name: name,
        assertions: Stack.make()
    }

    callback()

    Map.set(name, currentTestDef, tests)
}

let runSingleTest = (definition) => { 
    let wasSuccessfull = box(false)
    let errorBuffer = Buffer.make(5)
    let test = unbox(definition)
    let testName = test.name

    while(!Stack.isEmpty(test.assertions)) {
        let assertion = Option.unwrap(Stack.pop(test.assertions))

        let result = assertion()

        if(Option.isSome(result)) {
            let error = Option.unwrap(result)

            Buffer.addString("\t" ++ error ++ "\n", errorBuffer)
        }
        else {
            wasSuccessfull := true
        }
    }

    if(unbox(wasSuccessfull)) {
        print(testName ++ " successfull")
    }
    else {
        print(testName ++ " failed:")
        print(Buffer.toString(errorBuffer))
    }
}

provide let run = (testName) => {
    match(Map.get(testName, tests)) {
        Some(definition) => runSingleTest(definition),
        None => print(testName ++ " not found")
    }
}

provide let runAll = () => {
    Map.forEach((key, value) => runSingleTest(value), tests)
}

let pushAssertion = (toCheck, message) => {
    let check = () => {
        if(toCheck) {
            None()
        }
        else {
            Some(message)
        }
    }

    Stack.push(check, unbox(currentTestDef).assertions)
}

provide let assertEq = (expected, actual) => {
    pushAssertion(expected == actual,
        "expected " ++ toString(expected) ++ " but got " ++ toString(actual))
}

provide let assertTrue = (actual) => {
    pushAssertion(actual, "expected to be 'true' but was 'false'")
}

provide let assertFalse = (actual) => {
    pushAssertion(!actual, "expected to be 'false' but was 'true'")
}

provide let assertOk = (value) => {
    pushAssertion(Result.isOk(value), "expected to be ok")
}
